### ISSUE TITLE
Pipelines are not being triggered when gitness is deployed behind reverse proxy

### ISSUE THREAD

**Issue by MarioGK-AutoSystem** [harness/gitness#3395]
Hello, i started moving away all my repositories from github and github actions to gitness.

I have a VPS running gitness inside a docker container using the following docker compose file:

```yaml
version: '3.3'
services:
  gitness:
    ports:
      - '3000:3000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data:/data'
    container_name: gitness
    restart: always
    image: harness/gitness
    environment:
      GITNESS_USER_SIGNUP_ENABLED: false
      GITNESS_NESTED_SPACES_ENABLED: true
      GITNESS_URL_BASE: https://$DOMAIN
      GITNESS_URL_GIT: https://$DOMAIN/git
      GITNESS_URL_API: https://$DOMAIN/api
      GITNESS_URL_UI: https://$DOMAIN
      GITNESS_HTTP_PROTO: https
      GITNESS_CI_PARALLEL_WORKERS: 4
```
OBS: replaced my actual domain name with $DOMAIN

The gitnes is being served behind a caddy reverse proxy:
```
$DOMAIN {
        reverse_proxy localhost:3000
}
```

The pipeline:

```yaml
version: 1
kind: pipeline
spec:
  stages:
    - name: build
      type: ci
      spec:
        steps:
          - name: build
            type: run
            spec:
              container: mcr.microsoft.com/dotnet/sdk:8.0
              envs:
                SLEET_FEED_CONNECTIONSTRING: ${{secrets.get("SLEET_FEED_CONNECTIONSTRING")}}
                SLEET_FEED_CONTAINER: ${{secrets.get("SLEET_FEED_CONTAINER")}}
                SLEET_FEED_TYPE: ${{secrets.get("SLEET_FEED_TYPE")}}
              script: |-
                dotnet nuget add source https://$DOMAIN/sleet/index.json --name sleet
                dotnet tool install -g sleet
                export PATH="$PATH:/root/.dotnet/tools"
                export NUGET_VERSION=$(date --utc '+%Y.%m.%d.%H%M' | sed 's/\.\(0*\)/./g')
                echo $NUGET_VERSION
                dotnet pack ./src/AutoSystem.Devops/AutoSystem.Devops.csproj -p:PackageVersion=$NUGET_VERSION -o ./nuget
                sleet push ./nuget --skip-existing
```

Using the UI, API, cloning projects and running pipelines manually are all working correctly, but when i commit something the pipelines are not being triggered, am i missing a configuration about webhooks or something?
