### ISSUE TITLE
Failed to authenticate with credentials on repository

### ISSUE THREAD

**Issue by m10rten** [harness/gitness#3396]
I have the following compose, nothing else (yet):
```yaml
name: gitness
services:
  ship:
    image: harness/gitness:latest
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gitness:/data
      - gitness:/app
    restart: always
volumes:
  gitness: {}
```

In app I created the following credentials, on `localhost:3000`

UID: `a`
email: `test@test.ts`
password: `Test123`

And I was able to sign in, in the web UI.

But once I created a private repository and tried to pull, I was asked to authenticate (obviously since it is a new remote) so I tried with both UID + pass & email + pass.
Both failed on me, even after resetting the password and getting: `xnL23vsZRX` : a generated pass from gitness, it still failed for UID and email.

So what could I be doing wrong?
