### ISSUE TITLE
matrix support list

### ISSUE THREAD

**Issue by willzhang** [harness/gitness#3415]
this work
```
kind: pipeline
spec:
  stages:
  - type: ci
    spec:
      steps:
      - name: test
        type: script
        strategy:
          type: matrix
          spec:
            axis:
              node_version: [ "12", "14" ]
        spec:
          image: node:${{ matrix.node_version }}
          run: |-
            npm install
            npm test
```
but this not work, i have a long list , so i hope list them as a list wilth `- 12 -14`
```
kind: pipeline
spec:
  stages:
  - type: ci
    spec:
      steps:
      - name: test
        type: script
        strategy:
          type: matrix
          spec:
            axis:
              node_version: 
                - 12
                - 14
        spec:
          image: node:${{ matrix.node_version }}
          run: |-
            npm install
            npm test
```
