### ISSUE TITLE
DRONE_BUILD_ environment variables not being updated in same stage

### ISSUE THREAD

**Issue by casdr** [harness/gitness#3425]
This is a followup on issue https://github.com/drone-plugins/drone-slack/issues/162#issuecomment-1788143538.

I noticed that (at least) the `DRONE_BUILD_` environment variables aren't updated across steps in the same stage. 

For example, when having a step after a failed build, I'm getting the following result

```
[..]
export CI_BUILD_STARTED='0'
export CI_BUILD_STATUS='pending'
[..]
export DRONE_BUILD_STATUS='success'
[..]
```

I think this behaviour is incorrect, but it might be a design choice.

**Comment by bradrydzewski** [comment]
@casdr I am not sure I fully understand the description.  The code snippets you provided will override the environment variable values inside the container that Drone set.  Also note that CI_ variables were deprecated many years ago and should not be used.

In terms of the `DRONE_BUILD_` variables not being set correctly by Drone I created this sample yaml which you can use to test out the behavior:

```
kind: pipeline
type: docker
name: default

steps:
- name: a
  image: alpine:3
  commands:
  - echo $DRONE_BUILD_STATUS

- name: b
  image: alpine:3
  commands:
  - echo $DRONE_BUILD_STATUS
  - exit 1

- name: c
  image: alpine:3
  commands:
  - echo $DRONE_BUILD_STATUS
  when:
    status: failure
```

You will note that Drone correctly updates the status:

```
[a:1] + echo $DRONE_BUILD_STATUS
[a:2] success
[b:3] + echo $DRONE_BUILD_STATUS
[b:4] success
[b:5] + exit 1
[c:6] + echo $DRONE_BUILD_STATUS
[c:7] failure
```

**Comment by casdr** [comment]
@bradrydzewski Sorry for the confusing description. The snippets I posted are the result of running the `export` command in a step, so this doesn't override the environment but shows the current state.

The `CI_` variables are showing the same result as the `DRONE_` variables. I've copied your exact config into my `.drone.yml` and changed the type to Kubernetes, but I'm still getting different results:

```
[a:1] + echo $DRONE_BUILD_STATUS
[a:2] success
[b:3] + echo $DRONE_BUILD_STATUS
[b:4] success
[b:5] + exit 1
[c:6] + echo $DRONE_BUILD_STATUS
[c:7] success
```

This makes me think the issue lies within the Kubernetes pipeline provider.

**Comment by casdr** [comment]
I'm not using the export command to override or set a variable, only for displaying the current variables, like this:

```
kind: pipeline
type: kubernetes
name: default

steps:
- name: a
  image: alpine:3
  commands:
  - export

```

I wasn't aware that the kubernetes runner is experimental, we've been running like this for a few years now. I'll see if I can look into the issue myself in the meantime.
