### ISSUE TITLE
Add configuration values for the Pipelines created containers

### ISSUE THREAD

**Issue by ignaciolg** [harness/gitness#3428]
I've tried to use my docker file template to deploy Gitness. 

In that docker file, I define specific networks for the stack, and usually, I run everything without exposing ports by exposing the services with a tunnel (Cloudflare) or a proxy (Traefik)

Following this approach I have found that it is not possible to run pipelines, as they create the Drone container expecting to have access to Gitness using the 'http://host.docker.internal:3000/' address, instead of 'http://container_name:3000', accessible from the same docker network.

This results in an error on the first step of the pipeline that says 'unable to access 'http://host.docker.internal:3000/'

Changing the docker file by exposing the port makes it work.

It should be possible to specify the network for the newly created containers + where to find Gitness, as docker environment variables that can be passed on the container creation or as part of any docker file

**Comment by cozyGalvinism** [comment]
+1, am running into the same issue. I am running Gitness behind Traefik and this is pretty annoying.

**Comment by bradrydzewski** [comment]
> Following this approach I have found that it is not possible to run pipelines, as they create the Drone container expecting to have access to Gitness using the 'http://host.docker.internal:3000/' address

I believe this is configurable using GITNESS_URL_CONTAINER
https://github.com/harness/gitness/blob/a9895959ca593d81fc4a9da7a8e26ac77572ca97/types/config.go#L104

**Comment by indaco** [comment]
Hello,
any update on this?

@bradrydzewski `GITNESS_URL_CONTAINER` (not documented at all, [Configuration](https://docs.gitness.com/reference/configuration)) is the one I thought could work but... it does not.

Here is a simple _docker-compose.yml_ file with just `traefik` and `gitness`

```yaml
version: '3.8'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - '80:80/tcp'
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./logs/:/logs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=web'

  gitness:
    container_name: gitness
    image: harness/gitness
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GITNESS_URL_BASE=http://gitness.localhost
      - GITNESS_HTTP_PORT=3000
      - GITNESS_URL_CONTAINER=http://gitness.localhost
      - GITNESS_USER_SIGNUP_ENABLED=false
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=password
    volumes:
      - gitness_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.gitness.loadbalancer.server.port=3000'
      - 'traefik.http.routers.gitness.rule=Host(`gitness.localhost`)'
      - 'traefik.http.routers.gitness.entrypoints=web'

volumes:
  gitness_data:
    name: 'gitness_data'
```

`traefik` confile file is a basic one, nothing special

```yaml
# API and dashboard configuration
api:
  # Dashboard
  dashboard: true
  insecure: false

# Docker configuration backend
providers:
  docker:
    watch: true
    exposedByDefault: false
    swarmMode: false

# Traefik Logging & Access Logging
log:
  level: ERROR
  filePath: /logs/traefik.log
accesslog:
  filePath: /logs/traefik_access.log

# Entrypoint
entryPoints:
  web:
    address: ':80'
```

With this setup I can create project/repo/pipeline, clone, commit etc. All is working fine except **running** the pipeline failing at the _clone_ step.

```
Cloning with 0 retries Initialized empty Git repository in /gitness/.git/ + git fetch origin +refs/heads/main: fatal: unable to access 'http://gitness.localhost/git/playground/go-hello.git/': Failed to connect to gitness port 80 after 2 ms: Connection refused 
```

I tried severals values for `GITNESS_URL_CONTAINER` but no way. E.g.

```
- GITNESS_URL_CONTAINER=http://gitness.localhost
- GITNESS_URL_CONTAINER=http://<container_name>
- GITNESS_URL_CONTAINER=http://<container_name>:3000
- GITNESS_URL_CONTAINER=http://127.0.0.1:3000
- GITNESS_URL_CONTAINER=http://<internal_container_ip>:3000
```

I tried to set the `GITNESS_URL_INTERNAL` env variable too

https://github.com/harness/gitness/blob/a9895959ca593d81fc4a9da7a8e26ac77572ca97/types/config.go#L95-L97

Who can help? Thanks

**Comment by vistaarjuneja** [comment]
@ignaciolg @indaco @cozyGalvinism thanks for trying out Gitness and for your insight!
I think I understand the problem - currently we didn't have a way in gitness so that all created containers get added to a specific network or list of networks (this functionality does exist in drone: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-networks/).

I think that small bit should solve this issue where that env variable can be added to the gitness container docker-compose (say `GITNESS_CI_CONTAINER_NETWORKS=my_net`) and then gitness and all created containers would run on the same network. So that, along with the set value of `GITNESS_URL_CONTAINER` should allow all containers to interact with gitness.

Let me know if the above makes sense - I do have a PR up for this and have done a basic sanity check but would be great to hear from you if you think there's a use case that's not being solved.  Thanks!

**Comment by vistaarjuneja** [comment]
Hi folks, the above has been merged and will be available in the next release. We'll update the documentation with this use case. Let me know if you have any thoughts - thanks!

**Comment by alex-dna-tech** [comment]
To fix my issue #3485 i use [GITNESS_URL_CONTAINER](https://github.com/harness/gitness/blob/ac7ac5e881a444407ae1fafff7429844d1fff1c3/types/config.go#L82) to change route to external domain.

```yml
version: "3"
services:
  gitness:
    image: harness/gitness
    restart: unless-stopped
    volumes:
      - data/gitness:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITNESS_URL_BASE=https://gitness.${DOMAIN}
      - GITNESS_URL_CONTAINER=https://gitness.${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitness.rule=Host(`gitness.${DOMAIN}`)"
      - "traefik.http.routers.gitness.entrypoints=websecure"
      - "traefik.http.routers.gitness.service=gitness-svc"
      - "traefik.http.services.gitness-svc.loadbalancer.server.port=3000"
```
