### ISSUE TITLE
Slow loading at each page refresh

### ISSUE THREAD

**Issue by lcfd** [harness/gitness#3471]
Hi!

I'm running Gitness behind Traefik.
It's working fine, but the loading time at each page refresh is long and strange.
Once loaded the UX is smooth and quick.

Apparently Memory consumption is more than ok.

![CleanShot 2024-02-05 at 17 36 25](https://github.com/harness/gitness/assets/9001053/473e6af0-8c8b-4c26-90b7-616e2d04cbd5)

Here is the service in `docker-compose.yml`.

```
  gitness:
    container_name: gitness
    image: harness/gitness
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitness.tls=true
      - traefik.http.routers.gitness.entrypoints=websecure
      - traefik.http.routers.gitness.tls.certresolver=letsencrypt
      - traefik.http.routers.gitness.rule=Host(`gitness.my.domain`)
      - traefik.http.services.gitness.loadbalancer.server.port=3000
    environment:
      - GITNESS_URL_BASE=https://gitness.my.domain
      - GITNESS_USER_SIGNUP_ENABLED=false
      - GITNESS_DEBUG=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitness:/data
    networks:
      - traefik_proxy
```

Am I missing something? Thank you for your help.
