### ISSUE TITLE
How to deloy it offline, start up fail. could not populate plugins | error=could not download remote zip: could not get zip from url: Get "https://github.com/bradrydzewski/plugins/archive/refs/heads/master.zip": unexpected EOF

### ISSUE THREAD

**Issue by Innei** [harness/gitness#3482]
Hello,

I can't start service in an offline environment.

```
2024-03-06T07:28:50.833937727Z INF No valid profiler so skipping profiling [''] 
2024-03-06T07:28:50.841591811Z INF Completed setup of system service 'gitness' (id: 1). 
2024-03-06T07:28:50.841789273Z INF Completed setup of pipeline service 'pipeline' (id: 2). 
2024-03-06T07:28:50.841829845Z INF server started | port=80 revision= repository= version=0.0.1
2024-03-06T07:28:50.845367384Z ERR could not populate plugins | error=could not download remote zip: could not get zip from url: Get "https://github.com/bradrydzewski/plugins/archive/refs/heads/master.zip": unexpected EOF
```

May be this related issue is outdated. https://github.com/harness/gitness/issues/1572

**Comment by jimsheldon** [comment]
That file provides the plugins available to Gitness pipelines. You could host that file in a different location with the `GITNESS_CI_PLUGINS_ZIP_URL` variable, see https://github.com/harness/gitness/blob/v3.0.0-beta.6/types/config.go#L138-L141

**Comment by johannesHarness** [comment]
@Innei just following up on this. Did the environment variable mentioned by @jimsheldon above solve your problem?

**Comment by Innei** [comment]
Sorry, I haven't related this information lately, so I didn't follow up in time, I'll try to

**Comment by Innei** [comment]
Maybe not work, I add env in docker-compose file like this.


```yaml
name: gitness
services:
    gitness:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./gitness:/data
        container_name: gitness
        restart: always
        image: harness/gitness:latest
        environment:
          - GITNESS_HTTP_PORT=80
          - GITNESS_URL_BASE=http://git.innei.in
          - GITNESS_USER_SIGNUP_ENABLED=false
          - GITNESS_CI_PLUGINS_ZIP_URL=https://ghproxy.org/https://github.com/bradrydzewski/plugins/archive/refs/heads/master.zip # Add this
```

But still got an error, download file from github
```
{"level":"error","error":"could not download remote zip: could not get zip from url: Get \"https://github.com/bradrydzewski/plugins/archive/refs/heads/master.zip\": unexpected EOF","time":"2024-05-04T11:10:15.12901532Z","message":"could not populate plugins"}
```
