### ISSUE TITLE
Drone template extension invalid with .yaml and .yml

### ISSUE THREAD

**Issue by joaostorrer** [harness/gitness#3489]
I created a yaml file named `test.yaml` with this configuration:

```yaml
kind: pipeline
type: docker
name: default
steps:
   - name: {{ .input.name }}
     image: {{ .input.image }}
     commands:
        - {{ .input.commands }}
```

But when I try to add the template with the command `drone template add --namespace test --name test --data @test.yaml` it raises this error:

client error 400: {"message":"Template extension invalid. Must be yaml, starlark or jsonnet"}

I tried to change the extension to `.yml`, execute the command without the "@", pass the full path of the file, but the error continues.

I'm using CentOS 7.
