### ISSUE TITLE
Error: pipelines clone

### ISSUE THREAD

**Issue by dreemhai** [harness/gitness#3534]
I have configured a project using Gitness, and my Git submissions are functioning correctly with 'main' as the branch name. However, I encountered errors in the pipelines at the initial step. The error message is as follows. I installed the setup using the Docker configuration provided on the official website. Below are my Docker configuration and pipelines configuration details. Additionally, I did not identify any apparent errors in the Docker logs. Could you please advise on how to resolve this issue?

docker config:
```
version: "3"
services:
  gitness:
    image: harness/gitness
    container_name: gitness
    environment:
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=xxxxxxx
      - GITNESS_USER_SIGNUP_ENABLED=false
    networks:
      - traefik
    labels:
      - traefik.http.routers.gitness1.rule=Host(`gitness.home.com`)
      - traefik.http.routers.gitness.entrypoints=http
      - traefik.http.services.gitness.loadbalancer.server.port=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/gitness/data:/data
    restart: always
networks:
  traefik:
    external: true
```

pipeline config
```
kind: pipeline
spec:
  stages:
   - type: ci
     spec:
       steps:
       - name: build
         type: plugin
         spec:
           name: docker
           inputs:
            add_host: "8080"
            compress: true
            dockerfile: Dockerfile
            pull_image: true
            purge: "true"
            registry: registry.home.com
            tags:
              - latest
```

error message:
```
Cloning with 0 retries
Initialized empty Git repository in /gitness/.git/
+ git fetch origin +refs/heads/main:
fatal: couldn't find remote ref refs/heads/main
```
